import{a as w,S as E,i as n}from"./assets/vendor-hwdYKDic.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const q="48830775-40ff68ea61f2bc47ba43ee541",S="https://pixabay.com/api/",v=40;async function m(r,t){try{return(await w.get(S,{params:{key:q,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:v}})).data}catch(s){throw console.error("Error fetching data from Pixabay API:",s),s}}const P=new E(".gallery a",{captionsData:"alt",captionDelay:250});function f(r,t=!1){const s=document.querySelector("#gallery");t&&(s.innerHTML="");const c=r.map(({largeImageURL:e,webformatURL:o,tags:l,likes:h,views:y,comments:b,downloads:L})=>`
    <a href="${e}" class="gallery-item">
      <img src="${o}" alt="${l}" />
      <div class="image-info">
        <p><b>Likes</b> ${h}</p>
        <p><b>Views</b> ${y}</p>
        <p><b>Comments</b> ${b}</p>
        <p><b>Downloads</b> ${L}</p>
      </div>
    </a>
  `).join("");s.insertAdjacentHTML("beforeend",c),P.refresh()}function R(){const r=document.querySelector(".gallery-item");let t=100;r&&(t=r.getBoundingClientRect().height),window.scrollBy({top:t*2,behavior:"smooth"})}const a={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loader:document.querySelector("#loader"),gallery:document.querySelector("#gallery"),loadMoreBtn:document.querySelector(".load-more-btn")},i={query:"",page:1,totalHits:0};function p(){a.loader.classList.remove("hidden")}function d(){a.loader.classList.add("hidden")}function g(){a.loadMoreBtn.classList.remove("hidden")}function u(){a.loadMoreBtn.classList.add("hidden")}a.form.addEventListener("submit",async r=>{if(r.preventDefault(),i.query=a.input.value.trim(),i.page=1,!i.query){n.error({title:"Error",message:"Oops! You forgot to enter a search term.",position:"topRight",timeout:2e3});return}p(),u();try{const{hits:t,totalHits:s}=await m(i.query,i.page);i.totalHits=s,d(),t.length===0?(f([],!0),n.info({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3})):(f(t,!0),t.length<i.totalHits&&g())}catch(t){d(),n.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),console.error("Error fetching images:",t)}});a.loadMoreBtn.addEventListener("click",async()=>{i.page+=1,u(),p();try{const{hits:r}=await m(i.query,i.page);d(),g(),r.length===0?(u(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})):(f(r),R(),i.page*40>=i.totalHits&&(u(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})))}catch(r){d(),n.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),console.error("Error fetching images:",r)}});
//# sourceMappingURL=index.js.map
