import{a as E,S as q,i as n}from"./assets/vendor-hwdYKDic.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();const S="48830775-40ff68ea61f2bc47ba43ee541",v="https://pixabay.com/api/",P=40;async function f(r,e){try{return(await E.get(v,{params:{key:S,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:P}})).data}catch(s){throw console.error("Error fetching data from Pixabay API:",s),s}}function m(r,e=!1){const s=document.querySelector("#gallery");e&&(s.innerHTML="");const c=r.map(({largeImageURL:o,webformatURL:l,tags:h,likes:y,views:b,comments:L,downloads:w})=>`
    <a href="${o}" class="gallery-item">
      <img src="${l}" alt="${h}" />
      <div class="image-info">
        <p><b>Likes</b> ${y}</p>
        <p><b>Views</b> ${b}</p>
        <p><b>Comments</b> ${L}</p>
        <p><b>Downloads</b> ${w}</p>
      </div>
    </a>
  `).join("");s.insertAdjacentHTML("beforeend",c),new q(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}function R(){const r=document.querySelector(".gallery-item");let e=100;r&&(e=r.getBoundingClientRect().height),window.scrollBy({top:e*2,behavior:"smooth"})}const a={form:document.querySelector("#search-form"),input:document.querySelector("#search-input"),loader:document.querySelector("#loader"),gallery:document.querySelector("#gallery"),loadMoreBtn:document.querySelector(".load-more-btn")},i={query:"",page:1,totalHits:0};function p(){a.loader.classList.remove("hidden")}function d(){a.loader.classList.add("hidden")}function g(){a.loadMoreBtn.classList.remove("hidden")}function u(){a.loadMoreBtn.classList.add("hidden")}a.form.addEventListener("submit",async r=>{if(r.preventDefault(),i.query=a.input.value.trim(),i.page=1,!i.query){n.error({title:"Error",message:"Oops! You forgot to enter a search term.",position:"topRight",timeout:2e3});return}p(),u();try{const{hits:e,totalHits:s}=await f(i.query,i.page);i.totalHits=s,d(),e.length===0?n.info({title:"Oops!",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",timeout:3e3}):(m(e,!0),e.length<i.totalHits&&g())}catch(e){d(),n.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),console.error("Error fetching images:",e)}});a.loadMoreBtn.addEventListener("click",async()=>{i.page+=1,u(),p();try{const{hits:r}=await f(i.query,i.page);d(),g(),r.length===0?(u(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})):(m(r),R(),i.page*40>=i.totalHits&&(u(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight",timeout:3e3})))}catch(r){d(),n.error({title:"Error",message:"Something went wrong! Please try again later.",position:"topRight",timeout:3e3}),console.error("Error fetching images:",r)}});
//# sourceMappingURL=index.js.map
